/**
 * Chart palettes, one per theme, generated and validated rather than chosen.
 *
 * Every theme used to share one of two sets, selected by a light/dark
 * `chartBase`. Light and Sepia therefore drew identical charts, as did Dark,
 * Midnight and Graphite - switching theme changed the page and left the data
 * alone, which is backwards, because the surface is the thing a series colour
 * has to survive. It was also measurably wrong: run against each real surface,
 * the two shared sets took a sub-3:1 contrast relief on three of the five
 * (worst: #eda100 at 2.01 on Sepia, and the dark set's #008300 at 2.82 on
 * Graphite, which carried the light set's green verbatim).
 *
 * These five sets need no relief anywhere. Each was searched against its own
 * surface and every one of them clears, measured by the vendored validator:
 *
 *   theme     adjacent CVD   normal-vision   trio all-pairs   min contrast
 *   light        14.0            24.5           18.5 / 24.5      3.40:1
 *   sepia        12.8            26.7           15.0 / 27.1      3.08:1
 *   dark         12.1            22.1           11.6 / 22.1      3.60:1
 *   midnight     12.3            21.2           11.2 / 21.0      3.63:1
 *   graphite     13.3            21.4           12.1 / 19.7      3.60:1
 *
 * against gates of 8.0 (CVD), 15.0 (normal vision) and 3.0:1 (contrast). The
 * shipped sets they replace cleared CVD at 8.4 and 9.1.
 *
 * Eight slots still pass ADJACENT (lines, bars, stacks) and only the first
 * three pass ALL-PAIRS (scatter, small multiples), so `sectorColor` returns
 * null past eight rather than reusing a hue, and the small multiples use one
 * hue for every panel - position and the panel label carry sector identity,
 * not colour, which is why that form survives 19 sectors when a 19-line chart
 * cannot.
 *
 * To change any colour here, edit web/scripts/build_palettes.mjs and re-run it;
 * do not hand-edit the tables. It prints exactly the blocks below along with
 * the report each set passed.
 */
import type { ThemeName } from "../theme";

/** Chart code keys on the theme, not on a light/dark base. There used to be a
 *  separate `ChartBase` union threaded through every chart for this, which is
 *  precisely what made two themes indistinguishable on the one part of the page
 *  that is supposed to respond to the surface. */
export type { ThemeName } from "../theme";

// ─── generated by web/scripts/build_palettes.mjs — do not hand-edit ───────────
/** Categorical slots 1-8. Ordered by the generator's bottleneck search, so
 *  neighbouring slots are the furthest apart the set allows - that ordering is
 *  what the adjacent pairlist is measured on. */
const CATEGORICAL = {
  light: ["#84330b", "#1d9680", "#2e4aa3", "#a7821a", "#7e439e", "#548716", "#952a5b", "#1d92b2"],
  sepia: ["#a2351b", "#1f9e7c", "#154b9f", "#b6831c", "#70419e", "#76971b", "#9f3971", "#1f9ab2"],
  dark: ["#cd6987", "#477f2e", "#22a3d0", "#b35925", "#23ab9b", "#985aac", "#b1921e", "#5d6ebb"],
  midnight: ["#9f5799", "#9e961d", "#359ddc", "#ca7b2f", "#23a9aa", "#b84f5b", "#8b85df", "#3f9c5b"],
  graphite: ["#bf649a", "#768b19", "#5697e8", "#c66658", "#21a0b3", "#ad7719", "#9274c4", "#23ae81"],
} as const;

/** The one hue behind every sparkline, every small-multiple panel and the
 *  close-price line - by area the most visible colour in the app. It is the
 *  member of the theme's own set nearest ink navy, the design direction's own
 *  register, except on Midnight, whose ground IS navy: a navy lead there would
 *  be the exact failure the generator's avoid-arc exists to prevent, so it
 *  takes the member nearest amber instead. */
const PRIMARY = {
  light: "#2e4aa3",
  sepia: "#154b9f",
  dark: "#22a3d0",
  midnight: "#ca7b2f",
  graphite: "#5697e8",
} as const;

/** Context neutrals, carrying the surface's own hue at near-zero chroma. The
 *  moving averages behind an emphasised close price are these: they have to
 *  read as background on THIS surface, which is why Sepia's are warm and
 *  Midnight's are cool rather than one grey serving both. */
const CONTEXT_GREYS = {
  light: ["#717579", "#91969a", "#b0b5b9"],
  sepia: ["#76746f", "#979590", "#b6b4af"],
  dark: ["#84837e", "#666661", "#4d4d48"],
  midnight: ["#818388", "#64666b", "#4b4d52"],
  graphite: ["#828288", "#65656b", "#4c4c51"],
} as const;

/** Diverging poles for correlation: warm and cool, with a neutral midpoint that
 *  reads as "nothing" on this surface. The midpoint is the tell - a diverging
 *  scale whose centre looks like a colour makes zero correlation look like a
 *  result. blue-to-aqua was rejected upstream for exactly that reason: two cool
 *  hues, and a midpoint that reads as a value. */
const DIVERGING = {
  light: { negative: "#2168bb", mid: "#ebeff2", positive: "#9b2c27" },
  sepia: { negative: "#2168bb", mid: "#f0eeea", positive: "#9b2c27" },
  dark: { negative: "#5391de", mid: "#31312d", positive: "#d97066" },
  midnight: { negative: "#5391de", mid: "#2f3033", positive: "#d97066" },
  graphite: { negative: "#5b96e0", mid: "#303033", positive: "#da7369" },
} as const;
// ─── end generated ────────────────────────────────────────────────────────────

/** The first three slots are the only ones that validate all-pairs. */
export const SCATTER_HUE_CAP = 3;

/** Colour for a sector, assigned by position in `sectors`.
 *
 * Takes the caller's sector list rather than a fixed global order, because the
 * universe now has 19 sectors and the old SECTOR_ORDER only knew five - an
 * unknown sector fell back to slot 0 and rendered in Technology's blue with no
 * error. Past the categorical cap this returns null so the caller must decide
 * (fold to "Other", or facet); it never wraps around and reuses a hue. */
export function sectorColor(
  sector: string,
  sectors: readonly string[],
  theme: ThemeName,
): string | null {
  const index = sectors.indexOf(sector);
  const slots = CATEGORICAL[theme];
  if (index < 0 || index >= slots.length) return null;
  return slots[index]!;
}

/** Neutral for anything past the categorical cap. */
export function otherColor(theme: ThemeName): string {
  return CONTEXT_GREYS[theme][0]!;
}

/** Stock and crypto take slots 1 and 2 - the scatter is an all-pairs form and
 *  those are inside the validated three. */
export function assetTypeColor(assetType: string, theme: ThemeName): string {
  return assetType === "crypto" ? CATEGORICAL[theme][1] : CATEGORICAL[theme][0];
}

/** Series colours for an EMPHASIS form, not a categorical one: the close price
 *  is the subject and the moving averages are context. Giving each MA its own
 *  categorical hue would imply four peer series and bury the point. */
export function emphasisColors(theme: ThemeName) {
  // A keyed lookup, not a ternary. The ternary this replaced silently returned
  // the dark greys for any value that was not exactly "light", so adding a
  // theme would have compiled and been wrong.
  return { primary: PRIMARY[theme], context: [...CONTEXT_GREYS[theme]] };
}

/** Continuous mix across the diverging scale. `t` in [-1, 1]. */
export function divergingColor(t: number, theme: ThemeName): string {
  const { negative, mid, positive } = DIVERGING[theme];
  const clamped = Math.max(-1, Math.min(1, t));
  const target = clamped < 0 ? negative : positive;
  return mixHex(mid, target, Math.abs(clamped));
}

function mixHex(from: string, to: string, amount: number): string {
  const a = hexToRgb(from);
  const b = hexToRgb(to);
  const mix = (x: number, y: number) => Math.round(x + (y - x) * amount);
  return rgbToHex(mix(a[0], b[0]), mix(a[1], b[1]), mix(a[2], b[2]));
}

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbToHex(r: number, g: number, b: number): string {
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
}

/** Relative luminance, for choosing ink that clears contrast inside a filled cell. */
export function inkOn(background: string): string {
  const [r, g, b] = hexToRgb(background).map((v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  }) as [number, number, number];
  const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return luminance > 0.45 ? "#0b0b0b" : "#ffffff";
}

/** Mark specs, fixed across every chart in this app. */
export const MARK = {
  lineWidth: 2,
  contextLineWidth: 1.5,
  markerRadius: 4.5, // >= 8px diameter
  surfaceRing: 2,
  areaOpacity: 0.1,
} as const;
