/**
 * Chart palettes, one per theme, searched against that theme's own surface.
 *
 * Four gates, all measured by web/scripts/build_palettes.mjs: adjacent-pair
 * separation under simulated CVD (>= 8.0), under normal vision (>= 15.0),
 * contrast against the surface (>= 3.0:1), and OKLab dE >= 15 from all four
 * accents in the base, so a button is never the colour of a line.
 *
 * Eight slots pass ADJACENT (lines, bars, stacks); only the first three pass
 * ALL-PAIRS (scatter, small multiples). `sectorColor` returns null past eight
 * rather than reusing a hue.
 *
 * To change a colour, edit the generator and re-run it. Do not hand-edit the
 * tables below; it prints them along with the report each set passed.
 */
import type { ThemeName } from "../theme";

/** Chart code keys on the theme, not on a light/dark base: the surface is what
 *  a series colour has to survive. */
export type { ThemeName } from "../theme";

// ─── generated by web/scripts/build_palettes.mjs — do not hand-edit ───────────
/** Categorical slots 1-8, ordered so neighbouring slots are the furthest apart
 *  the set allows. That ordering is what the adjacent pairlist is measured on. */
const CATEGORICAL = {
  light: ["#1f98b3", "#d26443", "#1246ac", "#1f9c7e", "#905dbc", "#6b921a", "#d41d88", "#b1831b"],
  dark: ["#cd6987", "#477f2e", "#22a3d0", "#b35925", "#23aa99", "#985aac", "#b1921e", "#5d6ebb"],
  midnight: ["#359ddc", "#797314", "#9f5799", "#3f9c5b", "#8b85df", "#ca7b2f", "#22a6a7", "#b84f5b"],
  graphite: ["#bf649a", "#768b19", "#5697e8", "#d86c5c", "#22a5b8", "#ad7719", "#9f7fd5", "#23ae81"],
  sepia: ["#bb538a", "#76971b", "#8119ca", "#b6831c", "#1f9ab2", "#c7583e", "#346cc4", "#1f9e7c"],
} as const;

/** The one hue behind every sparkline, every small-multiple panel and the
 *  close-price line: by area the most visible colour in the app.
 *
 *  All five are chosen jointly, one member per theme, 8^5 combinations searched
 *  with dE >= 15 between every pair as a hard floor and the per-theme target
 *  hue deciding among what clears it. Chosen independently they converge on the
 *  same navy and four themes draw identical charts. check_palettes.mjs
 *  re-measures the floor. */
const PRIMARY = {
  light: "#1246ac",
  dark: "#22a3d0",
  midnight: "#ca7b2f",
  graphite: "#bf649a",
  sepia: "#76971b",
} as const;

/** Context neutrals, carrying the surface's own hue at near-zero chroma, so
 *  Sepia's are warm and Midnight's cool rather than one grey serving both.
 *  The moving averages behind an emphasised close price are these. */
const CONTEXT_GREYS = {
  light: ["#717579", "#91969a", "#b0b5b9"],
  dark: ["#84837e", "#666661", "#4d4d48"],
  midnight: ["#818388", "#64666b", "#4b4d52"],
  graphite: ["#828288", "#65656b", "#4c4c51"],
  sepia: ["#76746f", "#979590", "#b6b4af"],
} as const;

/** Diverging poles for correlation. The midpoint has to read as "nothing" on
 *  its surface: a scale whose centre looks like a colour makes zero
 *  correlation look like a result. */
const DIVERGING = {
  light: { negative: "#3379ce", mid: "#ebeff2", positive: "#cb584f" },
  dark: { negative: "#5391de", mid: "#31312d", positive: "#cb685e" },
  midnight: { negative: "#5391de", mid: "#2f3033", positive: "#cb685e" },
  graphite: { negative: "#5b96e0", mid: "#303033", positive: "#d86b61" },
  sepia: { negative: "#3379ce", mid: "#f0eeea", positive: "#cb584f" },
} as const;
// ─── end generated ────────────────────────────────────────────────────────────

/** The first three slots are the only ones that validate all-pairs. */
export const SCATTER_HUE_CAP = 3;

/** Colour for a sector, assigned by position in the caller's own `sectors`
 *  list rather than a fixed global order. Past the categorical cap it returns
 *  null so the caller must decide (fold to "Other", or facet); it never wraps
 *  around and reuses a hue. */
export function sectorColor(
  sector: string,
  sectors: readonly string[],
  theme: ThemeName,
): string | null {
  const index = sectors.indexOf(sector);
  const slots = CATEGORICAL[theme];
  if (index < 0 || index >= slots.length) return null;
  return slots[index]!;
}

/** Neutral for anything past the categorical cap. */
export function otherColor(theme: ThemeName): string {
  return CONTEXT_GREYS[theme][0]!;
}

/** Slots 1 and 2: the scatter is an all-pairs form, and those are inside the
 *  validated three. */
export function assetTypeColor(assetType: string, theme: ThemeName): string {
  return assetType === "crypto" ? CATEGORICAL[theme][1] : CATEGORICAL[theme][0];
}

/** Series colours for an EMPHASIS form, not a categorical one: the close price
 *  is the subject and the moving averages are context. Giving each MA its own
 *  categorical hue would imply four peer series. */
export function emphasisColors(theme: ThemeName) {
  // Keyed, not a ternary on "light": a ternary returns something plausible for
  // a theme it has never heard of, and compiles.
  return { primary: PRIMARY[theme], context: [...CONTEXT_GREYS[theme]] };
}

/** Continuous mix across the diverging scale. `t` in [-1, 1]. */
export function divergingColor(t: number, theme: ThemeName): string {
  const { negative, mid, positive } = DIVERGING[theme];
  const clamped = Math.max(-1, Math.min(1, t));
  const target = clamped < 0 ? negative : positive;
  return mixHex(mid, target, Math.abs(clamped));
}

function mixHex(from: string, to: string, amount: number): string {
  const a = hexToRgb(from);
  const b = hexToRgb(to);
  const mix = (x: number, y: number) => Math.round(x + (y - x) * amount);
  return rgbToHex(mix(a[0], b[0]), mix(a[1], b[1]), mix(a[2], b[2]));
}

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbToHex(r: number, g: number, b: number): string {
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
}

/** Relative luminance, for choosing ink that clears contrast inside a filled cell. */
export function inkOn(background: string): string {
  const [r, g, b] = hexToRgb(background).map((v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  }) as [number, number, number];
  const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return luminance > 0.45 ? "#0b0b0b" : "#ffffff";
}

/** Mark specs, fixed across every chart in this app. */
export const MARK = {
  lineWidth: 2,
  contextLineWidth: 1.5,
  markerRadius: 4.5, // >= 8px diameter
  surfaceRing: 2,
  areaOpacity: 0.1,
} as const;
